[workspace]

members = [
  "nannou",

  "sketches/cell_automata",
  "sketches/circle",
  "sketches/perlin",
  "sketches/soap_bubble",
  "sketches/waveclock",

  "utils/camera",
  "utils/rotation",
  "utils/screenshot",
]
